[workspace]
changelog_update = true
# Don't compare with crates.io (private repo)
registry = false

[[package]]
name = "ears"
changelog_path = "CHANGELOG.md"
git_release_enable = true
git_tag_enable = true
# Don't try to publish to crates.io
publish = false
